SELECT VILLA_ID FROM
(SELECT DISTINCT VILLA_ID, FEATURE_NAME 
FROM Z_VILLA_FEATURES,Z_FEATURES
WHERE Z_VILLA_FEATURES.FEATURE_ID=Z_FEATURES.FEATURE_ID
AND Z_FEATURES.FEATURE_NAME='Jacuzzi')
WHERE VILLA_ID NOT IN
(SELECT DISTINCT VILLA_ID
FROM Z_VILLA_FEATURES,Z_FEATURES
WHERE Z_VILLA_FEATURES.FEATURE_ID=Z_FEATURES.FEATURE_ID
AND Z_FEATURES.FEATURE_NAME='pets allowed' );
