SELECT USER_ID FROM
(SELECT R1.USER_ID FROM Z_RESERVATION R1, Z_RESERVATION R2
WHERE R1.USER_ID=R2.USER_ID
AND R1.START_DATE<R2.START_DATE 
AND R1.END_DATE>R2.START_DATE)
UNION
(SELECT R1.USER_ID FROM Z_RESERVATION R1, Z_RESERVATION R2
WHERE R1.USER_ID=R2.USER_ID
AND R1.START_DATE>R2.START_DATE 
AND R1.END_DATE<R2.START_DATE );
