SELECT Z_USER.FIRST_NAME, Z_USER.LAST_NAME, COUNT(Z_VILLA.VILLA_ID)
FROM Z_VILLA, Z_USER
WHERE Z_VILLA.OWNER_ID=Z_USER.USER_ID
GROUP BY Z_VILLA.OWNER_ID, Z_USER.FIRST_NAME, Z_USER.LAST_NAME
ORDER BY COUNT(Z_VILLA.VILLA_ID);
