SELECT DISTINCT Z_USER.FIRST_NAME, Z_USER.LAST_NAME 
FROM Z_RESERVATION,Z_USER,Z_COUPON
WHERE Z_COUPON.COUPON_ID=Z_RESERVATION.COUPON_ID
AND Z_RESERVATION.USER_ID=Z_USER.USER_ID 
AND Z_COUPON.DISCOUNT>10;
