SELECT  T.* FROM 
(SELECT  Z_USER.FIRST_NAME, Z_USER.LAST_NAME
FROM Z_USER,Z_RESERVATION
WHERE Z_USER.USER_ID=Z_RESERVATION.USER_ID
AND EXTRACT(YEAR FROM Z_RESERVATION.START_DATE)=2013
ORDER BY Z_RESERVATION.DEPOSIT DESC) T
WHERE ROWNUM<=3;
