SELECT  AVG(FLOOR(MONTHS_BETWEEN(Z_RESERVATION.START_DATE,Z_USER.DOB)/12)) Average_Age
FROM Z_USER,Z_RESERVATION
WHERE Z_USER.USER_ID=Z_RESERVATION.USER_ID
AND  Z_RESERVATION.START_DATE BETWEEN '2013/09/01' AND '2013/12/31';
