SELECT T.* FROM
(SELECT Z_VILLA.VILLA_ID,Z_USER.USER_ID
FROM Z_USER,Z_VILLA,Z_REVIEW
WHERE Z_REVIEW.VILLA_ID=Z_VILLA.VILLA_ID
AND Z_VILLA.OWNER_ID=Z_USER.USER_ID
GROUP BY Z_VILLA.VILLA_ID, Z_USER.USER_ID
ORDER BY AVG(Z_REVIEW.RATING) DESC) T
WHERE ROWNUM<=3;
