SELECT T.* FROM
(SELECT VILLA_ID, SUM(TRUNC( END_DATE-START_DATE) )AS NIGHTS
FROM Z_RESERVATION
WHERE EXTRACT(YEAR FROM START_DATE )=2014
GROUP BY VILLA_ID
ORDER BY SUM(TRUNC( END_DATE-START_DATE) ) DESC) T
WHERE ROWNUM=1;
