SELECT S.USER_ID FROM 
(SELECT T.USER_ID, COUNT (T.VILLA_ID) COUNT_VILLA FROM
(SELECT Z_REVIEW.USER_ID USER_ID,Z_REVIEW.VILLA_ID VILLA_ID, A.LIKEUSER, 
ROW_NUMBER() OVER (PARTITION BY Z_REVIEW.VILLA_ID ORDER BY A.LIKEUSER DESC) RN  FROM
(SELECT REVIEW_ID,COUNT(USER_ID) LIKEUSER
FROM Z_LIKEDREVIEWS 
GROUP BY REVIEW_ID) A
JOIN Z_REVIEW 
ON A.REVIEW_ID=Z_REVIEW.REVIEW_ID) T
WHERE T.RN=1
GROUP BY T.USER_ID
ORDER BY COUNT_VILLA DESC) S
WHERE ROWNUM=1;