DROP TABLE "SYSTEM"."Z_FAVORITE";
DROP TABLE "SYSTEM"."Z_LIKEDREVIEWS";

DROP TABLE "SYSTEM"."Z_RATE";

DROP TABLE "SYSTEM"."Z_RESERVATION";

DROP TABLE "SYSTEM"."Z_REVIEW";

DROP TABLE "SYSTEM"."Z_VILLA_FEATURES";

DROP TABLE "SYSTEM"."Z_COUPON";

DROP TABLE "SYSTEM"."Z_VILLA";

DROP TABLE "SYSTEM"."Z_OWNER";

DROP TABLE "SYSTEM"."Z_MANAGER";

DROP TABLE "SYSTEM"."Z_FEATURES";

DROP TABLE "SYSTEM"."Z_USER";